### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vi** [vi/compactmap#1]
@eddyb, What license shall it be?

Is there a recommended license for Rust open source libraries?

**Comment by eddyb** [comment]
It should probably be MIT. However, I would discuss with @bluss first, as they might want to have this in @contain-rs.

**Comment by bluss** [comment]
Most of contain-rs uses `MIT/Apache-2.0` which is the same as rust itself. Don't know if the organization has a license policy at all. It's a safe bet..
